### List All Data
GET {{baseUrl}}/data/


### Create Data
POST {{baseUrl}}/data/

{
  "name": "Data",
  "type": "Cool data type"
}

### Get Data Entry with ID
GET {{baseUrl}}/data/{{id}}

### Change Data Entry with ID
PUT {{baseUrl}}/data/{{id}}

{
  "name": "NEW NAME",
  "type": "Cool data type"
}

### Delete Data Entry with ID
DELETE {{baseUrl}}/data/{{id}}

